export const PLATFORM_CHAR_LIMITS: Record<string, number> = {
  TWITTER: 280,
  INSTAGRAM: 2200,
  FACEBOOK: 63206,
  LINKEDIN: 3000,
  YOUTUBE: 5000,
  TIKTOK: 2200,
  REDDIT: 40000,
  PINTEREST: 500,
  THREADS: 500,
  TELEGRAM: 4096,
  DISCORD: 2000,
  SLACK: 40000,
  MASTODON: 500,
  BLUESKY: 300,
  MEDIUM: 100000,
  DEVTO: 100000,
};

export const PLATFORM_TONES: Record<string, string> = {
  TWITTER: "concise, punchy, conversational with emojis",
  INSTAGRAM: "visual-focused, lifestyle, storytelling with emojis and hashtags",
  FACEBOOK: "conversational, community-focused, shareable",
  LINKEDIN: "professional, thought leadership, industry insights",
  YOUTUBE: "descriptive, SEO-optimized, with keywords",
  TIKTOK: "trendy, Gen-Z friendly, casual with trending sounds/hashtags",
  REDDIT: "informative, community-appropriate, no hard sells",
  PINTEREST: "aspirational, descriptive, keyword-rich",
  THREADS: "conversational, authentic, Twitter-like",
  TELEGRAM: "direct, informative, concise",
  DISCORD: "casual, community-focused, fun",
  SLACK: "professional, clear, actionable",
  MASTODON: "thoughtful, community-oriented, no algorithmic optimization",
  BLUESKY: "concise, authentic, early-adopter friendly",
  MEDIUM: "long-form, analytical, well-structured essay",
  DEVTO: "technical, educational, developer-focused with code examples",
};
