"use client";

import { buildStripInnerHtml, superTextAnchorCss, type SuperTextConfig } from "@postautomation/super-text";

/**
 * Live preview of the strip that will be BURNED into the video.
 *
 * It renders the EXACT output of the shared builder the worker feeds to Puppeteer —
 * one source of truth for the look. This is the direct lesson of the REP-4 revert:
 * a preview drawn by a second, parallel code path drifts from the baked artifact
 * (there: a duplicated logo and literal `**markup**` on screen), and the user ships
 * something they never saw.
 *
 * The injected HTML is machine-generated by buildStripInnerHtml, which escapes every
 * character of user text (escapeHtml) and validates every colour against /^#[0-9a-f]{6}$/
 * (safeHexColor) — no user-authored markup or attribute can reach the DOM. Same
 * discipline as packages/ai/src/tools/creative-templates.ts, locked by
 * packages/super-text/src/__tests__/super-text.test.ts.
 *
 * Sizing: font-size is fontSizePct% of the STAGE width, exactly as the burn uses
 * fontSizePct% of the VIDEO width — so the preview is a faithfully scaled model.
 */
export function SuperTextStrip({
  config,
  stageWidth,
}: {
  config: SuperTextConfig;
  stageWidth: number;
}) {
  const fontPx = (config.fontSizePct / 100) * stageWidth;
  // Width + alignment come from the SAME helper the burn frame uses, so a
  // layout preset (e.g. "insta": centred block, left-aligned lines) wraps at
  // the same words on the preview stage and on the video.
  const anchor = superTextAnchorCss(config);
  return (
    <div
      style={{
        position: "absolute",
        left: `${config.xPct}%`,
        top: `${config.yPct}%`,
        transform: "translate(-50%,-50%)",
        ...(anchor.width ? { width: anchor.width } : {}),
        maxWidth: anchor.maxWidth,
        textAlign: anchor.textAlign,
        fontSize: `${fontPx}px`,
        pointerEvents: "none",
      }}
      dangerouslySetInnerHTML={{ __html: buildStripInnerHtml(config) }}
    />
  );
}
